name = "LearnLean4"
version = "0.1.0"
defaultTargets = ["LearnLean4"]
testDriver = "LearnLean4Tests"

[[require]]
name = "LSpec"
git = "https://github.com/argumentcomputer/LSpec"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.0"

[[lean_lib]]
name = "LearnLean4"

[[lean_lib]]
name = "NaturalNumberGame"

# Test library (files under Tests/)
[[lean_lib]]
name = "Tests"

# Test executable entry point
[[lean_exe]]
name = "LearnLean4Tests"
